Sylius\Component\Core\Model\Customer:
    properties:
        orders: ~
        defaultAddress: ~
        addresses: ~
        user: ~
        email:
            faker: email
            unique: true
            prefix: 'anonymized-'
        emailCanonical:
            faker: email
            unique: true
            prefix: 'anonymized-'
        firstName:
            faker: firstName
            prefix: 'anonymized-'
        lastName:
            faker: lastName
            prefix: 'anonymized-'
        birthday:
            faker: dateTime
        gender:
            value: 'u'
        phoneNumber:
            faker: phoneNumber
            prefix: 'anonymized-'
        subscribedToNewsletter:
            faker: boolean
            args: [0]
