services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Synolia\SyliusGDPRPlugin\:
        resource: '../../*'
        exclude: '../../{SynoliaSyliusGDPRPlugin.php}'
