Sylius\Component\Core\Model\OrderItem:
    attributes:
        productName: &defaultGroup
            groups:
                - !php/const Synolia\SyliusGDPRPlugin\Enum\GDPRSerializationKeyEnum::CUSTOMER_DATA
        variantName: *defaultGroup
        quantity: *defaultGroup
        unitPrice: *defaultGroup
        total: *defaultGroup
        unitsTotal: *defaultGroup
        adjustments: *defaultGroup
        adjustmentsTotal: *defaultGroup
