Sylius\Component\Core\Model\Order:
    attributes:
        shippingAddress: &defaultGroup
            groups:
                - !php/const Synolia\SyliusGDPRPlugin\Enum\GDPRSerializationKeyEnum::CUSTOMER_DATA
        billingAddress: *defaultGroup
        payments: *defaultGroup
        shipments: *defaultGroup
        currencyCode: *defaultGroup
        localeCode: *defaultGroup
        promotionCoupon: *defaultGroup
        checkoutState: *defaultGroup
        paymentState: *defaultGroup
        shippingState: *defaultGroup
        promotions: *defaultGroup
        customerIp: *defaultGroup
        checkoutCompletedAt: *defaultGroup
        number: *defaultGroup
        notes: *defaultGroup
        items: *defaultGroup
        itemsTotal: *defaultGroup
        adjustments: *defaultGroup
        adjustmentsTotal: *defaultGroup
        total: *defaultGroup
        state: *defaultGroup
