Sylius\Component\Core\Model\Payment:
    attributes:
        method: &defaultGroup
            groups:
                - !php/const Synolia\SyliusGDPRPlugin\Enum\GDPRSerializationKeyEnum::CUSTOMER_DATA
        currencyCode: *defaultGroup
        amount: *defaultGroup
        state: *defaultGroup
        details: *defaultGroup
