Sylius\Component\Core\Model\Address:
    attributes:
        firstName: &defaultGroup
            groups:
                - !php/const Synolia\SyliusGDPRPlugin\Enum\GDPRSerializationKeyEnum::CUSTOMER_DATA
        lastName: *defaultGroup
        phoneNumber: *defaultGroup
        company: *defaultGroup
        countryCode: *defaultGroup
        provinceCode: *defaultGroup
        provinceName: *defaultGroup
        street: *defaultGroup
        city: *defaultGroup
        postcode: *defaultGroup
