Sylius\Component\Core\Model\Customer:
    attributes:
        user: &defaultGroup
            groups:
                - !php/const Synolia\SyliusGDPRPlugin\Enum\GDPRSerializationKeyEnum::CUSTOMER_DATA
        email: *defaultGroup
        emailCanonical: *defaultGroup
        defaultAddress: *defaultGroup
        addresses: *defaultGroup
        orders: *defaultGroup
        firstName: *defaultGroup
        lastName: *defaultGroup
        birthDay: *defaultGroup
        gender: *defaultGroup
        createdAt: *defaultGroup
        updatedAt: *defaultGroup
        phoneNumber: *defaultGroup
        subscribedToNewsletter: *defaultGroup
