Sylius\Component\Core\Model\Shipment:
    attributes:
        adjustments: &defaultGroup
            groups:
                - !php/const Synolia\SyliusGDPRPlugin\Enum\GDPRSerializationKeyEnum::CUSTOMER_DATA
        adjustmentsTotal: *defaultGroup
        state: *defaultGroup
        method: *defaultGroup
        tracking: *defaultGroup
        shippedAt: *defaultGroup
