Sylius\Component\Core\Model\ShopUser:
    attributes:
        username: &defaultGroup
            groups:
                - !php/const Synolia\SyliusGDPRPlugin\Enum\GDPRSerializationKeyEnum::CUSTOMER_DATA
        usernameCanonical: *defaultGroup
        lastLogin: *defaultGroup
        verifiedAt: *defaultGroup
        email: *defaultGroup
        emailCanonical: *defaultGroup
